feat: add test renderConditional
POSTPUNK-TELETUBIES/rulesAdmin pull request #259
Opened 2023-08-04 15:19 UTC by ChumanY

2023-08-04 15:24 UTC, Shadowrunner11 commented on src/tools/index.ts
> +) => (isRender ? trueValue : falseValue);
Tambien intercambiar el orden de los parametros

2023-08-04 15:24 UTC, Shadowrunner11 commented on test/renderConditional.test.ts
> +  const result = renderConditional(false, 'asdsa', 'zzzz');
Intercambiar tambienel orden de los argumentos

2023-08-04 15:25 UTC, Shadowrunner11 commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.22.5.tgz"
No debe cambiar el repositorio de los paquetes, del lock dependen los despliegues

2023-08-04 15:27 UTC, Shadowrunner11 commented on package-lock.json
No deberia existir este archivo

2023-08-06 23:13 UTC, Shadowrunner11 commented
Hay conflcitos por la instalacion del la libreria yup

2023-08-10 23:47 UTC, jaenfigueroa approved these changes

2023-08-11 15:41 UTC, Shadowrunner11 requested changes

2023-08-11 15:41 UTC, Shadowrunner11 commented on test/renderConditional.test.ts
> +});
Los test deben estar adentro de una suit
```ts
describe('conditional render', ()=>{
   test('render condition is true', ()=>...)
   test('render condition is false', ()=>...)
  })

2023-08-11 15:41 UTC, Shadowrunner11 commented on test/renderConditional.test.ts
> +  const result = renderConditional(false, 'asdsa', 'zzzz');
Se puede usar faker para los valores para q sea categorico el test

2023-08-16 15:41 UTC, Shadowrunner11 requested changes
El yarn lock se usa para el despliegue, no debe cambiar los sources, tampoco en local, xq esta cambiando?

2023-08-17 00:35 UTC, Shadowrunner11 approved these changes

2023-08-17 00:35 UTC, merged