feat: validation form yup
POSTPUNK-TELETUBIES/rulesAdmin pull request #274
Opened 2023-08-22 14:17 UTC by ChumanY

2023-08-22 16:45 UTC, Shadowrunner11 requested changes

2023-08-22 16:45 UTC, Shadowrunner11 commented on package.json
> +    "formik": "^2.4.3",
estamos usando react hook forms, formik es muy pesado. Desinstalar

2023-08-22 16:45 UTC, Shadowrunner11 commented on package.json
> +    "use-debounce": "^9.0.4",
Con react hook forms no y su respectivo resolver no es necesario un debounce

2023-08-22 16:45 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +});
Tipar schema, separar schema del componente

2023-08-22 17:00 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +      }
Al hacer uso de react hook form los errores se expondran para evitar el uso de try catch

2023-08-22 17:01 UTC, Shadowrunner11 approved these changes

2023-08-22 17:01 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +    if (error) {
Los if de una sola instruccion no necesitanbloque explicito

2023-08-22 17:01 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +    }
Los if de una sola instruccion no necesitan bloque explicito

2023-08-22 17:02 UTC, Shadowrunner11 requested changes

2023-08-22 17:02 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +
xq se coloco un slato de linea adicional?

2023-08-23 05:45 UTC, ChumanY commented on package.json
> +    "formik": "^2.4.3",
corregido

2023-08-23 05:45 UTC, ChumanY commented on src/components/Login/index.tsx
> +    if (error) {
corregido

2023-08-23 05:46 UTC, ChumanY commented on src/components/Login/index.tsx
> +
corregido

2023-08-23 05:46 UTC, ChumanY commented on src/components/Login/index.tsx
> +    }
corregido

2023-08-23 05:55 UTC, ChumanY commented on src/components/Login/index.tsx
> +});
corregido

2023-08-23 18:04 UTC, Shadowrunner11 requested changes

2023-08-23 18:04 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +    [enqueueSnackbar, resetField, setLoginInfo]
Debemos intentar hacer reaccionar ante el cambio de data de los hooks acciones q cuentan como efectos secundarios, no hacerlo imperativo

https://react.dev/learn/reacting-to-input-with-state#thinking-about-ui-declaratively
https://react.dev/learn/keeping-components-pure#side-effects-unintended-consequences

Ejemplo
```tsx
const { formState: {errors} } = useForm()

useEffect(()=>{
if(Object.values.some(Boolean))
enqueueSnackbar({
 // Parse errors deberia ser una funcion q cambia de objecto a string
  message: parseErrors(errors)
})
}, [errors])
```

2023-08-23 19:39 UTC, Shadowrunner11 requested changes

2023-08-23 19:39 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +    }
Los if de una sola condicion no neceistan bloque

2023-08-23 19:39 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
ya no es necesario el try catch el use Effect se encarga de mostrar el snackbar cunado haya errores, quitar linea 50

2023-08-23 19:39 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +  };
Funciones puras fuera del componente, sino causan problemas de optimizacion

Se puede lograr funcional puro
```ts
const parseErrors = (errors: Record<string, string>) => Object.entries(errors).reduce(([fieldname, value])=> `${fieldName}: ${value.message}\n`, '')
```

2023-08-24 17:20 UTC, Shadowrunner11 approved these changes

2023-08-24 17:20 UTC, Shadowrunner11 commented on src/components/Login/index.tsx
> +
```tsx
filter(([_, value])=> value?.message)
```

2023-08-24 17:21 UTC, merged